// Edge Function : {{SLUG}}
// HubSpot form : {{FORM_NAME_HUMAN}}
// Portal {{PORTAL_ID}} - Form {{FORM_ID}} - Region {{REGION}}
//
// Endpoint  : POST /functions/v1/{{SLUG}}
// Doc       : voir README.md dans ce dossier
//
// Generated by /hubspot-edge-form (~/.claude/skills/hubspot-edge-form/)

const HUBSPOT_PORTAL_ID = '{{PORTAL_ID}}'
const HUBSPOT_FORM_ID = '{{FORM_ID}}'
const SUBMIT_URL = `https://api{{REGION_SUFFIX}}.hsforms.com/submissions/v3/integration/submit/${HUBSPOT_PORTAL_ID}/${HUBSPOT_FORM_ID}`

// CORS : ajuster apres deploy avec ton URL prod
const ALLOWED_ORIGINS = [
  'http://localhost:4321',
  'http://localhost:5173',
  'http://localhost:3000',
  // 'https://your-prod-domain.com',
]

// === Enums extraits du form HubSpot ===
{{ENUM_DECLARATIONS}}

// === Type Payload accepte ===
{{FIELDS_TYPE}}

function corsHeaders(origin: string | null): Record<string, string> {
  const allowed = origin && ALLOWED_ORIGINS.includes(origin) ? origin : ALLOWED_ORIGINS[0]
  return {
    'Access-Control-Allow-Origin': allowed,
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Max-Age': '86400',
  }
}

function isValidEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) && email.length <= 254
}

// HubSpot rejette les hutk malformes (INVALID_HUTK).
// Le hutk authentique est un hex de 32 chars.
function sanitizeHutk(hutk: string | null | undefined): string | null {
  if (!hutk || typeof hutk !== 'string') return null
  return /^[a-f0-9]{32}$/i.test(hutk.trim()) ? hutk.trim() : null
}

function validate(body: Payload): string | null {
{{VALIDATION_BLOCK}}
  return null
}

function buildFields(body: Payload) {
  const out: Array<{ objectTypeId: string; name: string; value: string }> = []
  const push = (objectTypeId: string, name: string, value?: string) => {
    if (value && String(value).trim()) {
      out.push({ objectTypeId, name, value: String(value).trim() })
    }
  }
{{FIELDS_BUILDER}}
  return out
}

async function submitWithRetry(payload: object, maxRetries = 3): Promise<Response> {
  let delay = 800
  for (let attempt = 0; attempt < maxRetries; attempt++) {
    const res = await fetch(SUBMIT_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    })
    if (res.ok || (res.status >= 400 && res.status < 500 && res.status !== 429)) {
      return res
    }
    const retryAfter = parseInt(res.headers.get('retry-after') ?? '0', 10) * 1000
    await new Promise((r) => setTimeout(r, Math.max(delay, retryAfter)))
    delay *= 2
  }
  return fetch(SUBMIT_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  })
}

Deno.serve(async (req) => {
  const origin = req.headers.get('origin')
  const headers = { ...corsHeaders(origin), 'Content-Type': 'application/json' }

  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers })
  }

  if (req.method !== 'POST') {
    return new Response(
      JSON.stringify({ ok: false, error: 'Method not allowed' }),
      { status: 405, headers },
    )
  }

  let body: Payload
  try {
    body = await req.json()
  } catch {
    return new Response(
      JSON.stringify({ ok: false, error: 'JSON invalide' }),
      { status: 400, headers },
    )
  }

  if (body.honeypot) {
    return new Response(JSON.stringify({ ok: true }), { status: 200, headers })
  }

  const validationError = validate(body)
  if (validationError) {
    return new Response(
      JSON.stringify({ ok: false, error: validationError }),
      { status: 400, headers },
    )
  }

  const fields = buildFields(body)
  if (fields.length === 0) {
    return new Response(
      JSON.stringify({ ok: false, error: 'Aucun champ rempli' }),
      { status: 400, headers },
    )
  }

  const hubspotPayload = {
    submittedAt: Date.now(),
    fields,
    context: {
      hutk: sanitizeHutk(body.hutk),
      pageUri: body.pageUri ?? null,
      pageName: body.pageName ?? null,
      ipAddress: req.headers.get('x-forwarded-for')?.split(',')[0].trim() ?? null,
    },
  }

  const start = Date.now()
  let res: Response
  try {
    res = await submitWithRetry(hubspotPayload)
  } catch (err) {
    console.error(JSON.stringify({
      event: 'hubspot_submit_network_error',
      err: err instanceof Error ? err.message : String(err),
    }))
    return new Response(
      JSON.stringify({ ok: false, error: 'Erreur reseau HubSpot' }),
      { status: 502, headers },
    )
  }
  const latencyMs = Date.now() - start

  if (res.ok) {
    const data = await res.json().catch(() => ({}))
    console.log(JSON.stringify({
      event: 'hubspot_submit_success',
      status: res.status,
      latencyMs,
      fieldsCount: fields.length,
      hutkPresent: Boolean(hubspotPayload.context.hutk),
    }))
    return new Response(
      JSON.stringify({
        ok: true,
        hubspotMessage: data.inlineMessage || 'Submission acceptee',
        redirectUri: data.redirectUri ?? null,
      }),
      { status: 200, headers },
    )
  }

  const errorBody = await res.text()
  console.error(JSON.stringify({
    event: 'hubspot_submit_failure',
    status: res.status,
    latencyMs,
    body: errorBody.slice(0, 500),
  }))

  let parsedError: unknown
  try { parsedError = JSON.parse(errorBody) } catch { parsedError = errorBody }

  return new Response(
    JSON.stringify({
      ok: false,
      error: `HubSpot a rejete la submission (${res.status})`,
      details: parsedError,
    }),
    { status: res.status === 429 ? 429 : 502, headers },
  )
})
